language: php

sudo: false

dist: trusty

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - nightly

env:
    - SYMFONY_VERSION="4.4.*"
    - SYMFONY_VERSION="5.0.*"

matrix:
    fast_finish: true
    exclude:
        - php: 7.1
          env: SYMFONY_VERSION="5.0.*"
    allow_failures:
        - php: nightly

before_script:
    - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-dist --no-interaction --no-progress
    - mkdir -p build/logs
    - if [ "${TRAVIS_PHP_VERSION}" == '7.1' ] && [ "${SYMFONY_VERSION}" == '4.4.*' ]; then composer require doctrine/orm doctrine/doctrine-bundle doctrine/mongodb-odm-bundle alcaeus/mongo-php-adapter --ignore-platform-reqs --no-interaction --no-progress; fi;

script:
    - if [ "${TRAVIS_PHP_VERSION}" != '7.1' ] || [ "${SYMFONY_VERSION}" != '4.4.*' ]; then vendor/bin/phpunit -v; fi;
    - if [ "${TRAVIS_PHP_VERSION}" == '7.1' ] && [ "${SYMFONY_VERSION}" == '4.4.*' ]; then vendor/bin/phpunit -v --coverage-clover build/logs/clover.xml; fi;
    - if [ "${TRAVIS_PHP_VERSION}" == '7.1' ] && [ "${SYMFONY_VERSION}" == '4.4.*' ]; then travis_retry wget -q https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar && travis_retry php coveralls.phar -v; fi;

notifications:
    email:
        - hello@ingalabs.hu

cache:
    directories:
        - $HOME/.composer/cache
