language: php

sudo: false

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm
    - nightly

env:
    - SYMFONY_VERSION="2.7.*"
    - SYMFONY_VERSION="2.8.*"
    - SYMFONY_VERSION="3.2.*"
    - SYMFONY_VERSION="dev-master"

before_script:
    - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-dist --no-interaction --no-progress
    - mkdir -p build/logs
    - if [ "${TRAVIS_PHP_VERSION}" == '7.1' ] && [ "${SYMFONY_VERSION}" == '3.2.*' ]; then composer require doctrine/orm doctrine/doctrine-bundle doctrine/mongodb-odm-bundle alcaeus/mongo-php-adapter --ignore-platform-reqs --no-interaction --no-progress; fi;

script:
    - if [ "${TRAVIS_PHP_VERSION}" != '7.1' ] || [ "${SYMFONY_VERSION}" != '3.2.*' ]; then vendor/bin/phpunit -v; fi;
    - if [ "${TRAVIS_PHP_VERSION}" == '7.1' ] && [ "${SYMFONY_VERSION}" == '3.2.*' ]; then vendor/bin/phpunit -v --coverage-clover build/logs/clover.xml; fi;
    - if [ "${TRAVIS_PHP_VERSION}" == '7.1' ] && [ "${SYMFONY_VERSION}" == '3.2.*' ]; then travis_retry wget -q https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar && travis_retry php coveralls.phar -v; fi;

notifications:
    email:
        - hello@ingalabs.hu

cache:
    directories:
        - $HOME/.composer/cache
