services:
    ingalabs_image.image_controller:
        class: 'IngaLabs\Bundle\ImageBundle\Controller\ImageController'
        arguments: ['@ingalabs_image.image_manager']

    ingalabs_image.image_manager:
        class: 'IngaLabs\Bundle\ImageBundle\ImageManager'
        arguments: [~, []]

    ingalabs_image.routing_loader:
        class: 'IngaLabs\Bundle\ImageBundle\Routing\Loader\ImageLoader'
        arguments: [[]]
        tags:
            - { name: routing.loader }
