IngaLabs\Bundle\ImageBundle\Model\Image:
    type: entity
    repositoryClass: 'IngaLabs\Bundle\ImageBundle\Repository\Doctrine\ImageRepository'
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
